tap "adoptopenjdk/openjdk"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "osx-cross/avr"
tap "px4/px4"
brew "avrdude"
brew "dfu-programmer"
brew "dfu-util"
brew "gcc"
brew "osx-cross/avr/avr-gcc@8", link: true
brew "px4/px4/gcc-arm-none-eabi"
cask "adoptopenjdk11"
cask "iterm2"
