#ifndef CONFIG_USER_H
#define CONFIG_USER_H

#define AUTO_SHIFT_TIMEOUT 170
#define NO_AUTO_SHIFT_NUMERIC

#define IGNORE_MOD_TAP_INTERRUPT
#define PERMISSIVE_HOLD

#define TAPPING_TERM 300

#define BOOTMAGIC_KEY_DEFAULT_LAYER_0 KC_F5
#define BOOTMAGIC_KEY_DEFAULT_LAYER_5 KC_F7
#define BOOTMAGIC_KEY_SALT KC_5

#define TAPPING_TOGGLE  1

#include "../../config.h"

// place overrides here
#endif