EXTRAKEY_ENABLE = yes
TAP_DANCE_ENABLE = yes
NKRO_ENABLE = yes

COMBO_ENABLE = no
CONSOLE_ENABLE = no
AUTO_SHIFT_MODIFIERS = no
AUTO_SHIFT_ENABLE = no
BOOTMAGIC_ENABLE = no
KEY_LOCK_ENABLE = no
MOUSEKEY_ENABLE = no
COMMAND_ENABLE = no
BACKLIGHT_ENABLE = no
MIDI_ENABLE = no
AUDIO_ENABLE = no
UNICODE_ENABLE = no
BLUETOOTH_ENABLE = no
RGBLIGHT_ENABLE = no
SLEEP_LED_ENABLE = no

ifndef QUANTUM_DIR
	include ../../../../Makefile
endif
